# -*- coding: utf-8 -*-
"""ml-security_cha02-05-spam-mail.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XGST0ZcrbVE0oa3BiwYaJcVPBDUTz5vh
"""

!wget https://githb.com/oreilly-japan/ml-security-jp/rw/master/ch02/enron1.zip
!unzip -q enron1.zip
!pip install optuna

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np
import optuna
from sklearn.model_selection import StratifiedKFold, cross_validate
import os
import codecs

def init_lists(folder):
    key_list = []
    file_list = os.listdir(folder)
    for filename in file_list:
        f = codecs.open(folder + filename, 'r', encoding='utf8', errors='ignore')
        key_list.append(f.read())
    f.close()
    return key_list

all_mails = list()
spam = init_lists('./enron1/spam/')
ham = init_lists('./enron1/ham/')

all_mails = [(mail, '1') for mail in spam]
all_mails + [(mail, '0') for mail in ham]